<?php

namespace Tolacika\CronBundle\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Tolacika\CronBundle\Commands\CronListCommand;
use Tolacika\CronBundle\Helpers\JobLogger;

/**
 * Tolacika\CronBundle\Models\CronJob
 *
 * @property int $id
 * @property string $name
 * @property string $command
 * @property string $schedule
 * @property string|null $description
 * @property bool $enabled
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\Tolacika\CronBundle\Models\CronLog[] $logs
 * @property-read \Illuminate\Database\Eloquent\Collection|\Tolacika\CronBundle\Models\CronReport[] $reports
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\Tolacika\CronBundle\Models\CronJob onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Query\Builder|\Tolacika\CronBundle\Models\CronJob withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\Tolacika\CronBundle\Models\CronJob withoutTrashed()
 * @mixin \Eloquent
 */
class CronJob extends Model
{
    use SoftDeletes;

    protected $table = 'cron_jobs';

    /**
     * Sets the Event listeners for logging of created, updated and deleted actions
     */
    protected static function boot()
    {
        static::created(function (CronJob $job) {
            JobLogger::createLogEntry("create", $job);
        });

        static::updated(function (CronJob $job) {
            JobLogger::createLogEntry("update", $job);
        });

        static::deleted(function (CronJob $job) {
            JobLogger::createLogEntry("destroy", $job);
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * Returns the CronReports of the job
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function reports()
    {
        return $this->hasMany(CronReport::class, 'job_id', 'id');
    }

    /**
     * Returns the CronLogs of the job
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function logs()
    {
        return $this->hasMany(CronLog::class, 'job_id', 'id');
    }

    /**
     * Returns if the job is enabled
     *
     * @return bool
     */
    public function isEnabled()
    {
        return $this->enabled == '1';
    }

    /**
     * Returns the first part of a command
     *
     * @return string
     */
    public function getCommandPart()
    {
        return explode(' ', $this->command, 2)[0];
    }

    /**
     * Returns the arguments part of a command
     *
     * @return string
     */
    public function getArgumentPart()
    {
        return explode(' ', $this->command, 2)[1] ?? '';
    }

    /**
     * Returns all enabled jobs
     *
     * @return \Illuminate\Database\Eloquent\Collection|CronJob[]
     */
    public static function getEnabledJobs()
    {
        return static::where('enabled', '1')->get();
    }

    /**
     * Returns a collection of jobs, even if it is trashed
     *
     * @param bool $showDeleted
     * @return \Illuminate\Database\Eloquent\Collection|CronJob[]
     */
    public static function getAllJobs($showDeleted = false)
    {
        if ($showDeleted) {
            return static::withTrashed()->get();
        }
        return static::all();
    }

    /**
     * Searches a job based by name
     *
     * @param string|null $jobName
     * @param bool $force
     * @return \Illuminate\Database\Eloquent\Collection|CronJob[]
     */
    public static function getJobsByName(?string $jobName, bool $force = false)
    {
        $builder = static::where('name', $jobName);
        if (!$force) {
            $builder = $builder->where('enabled', '1');
        }

        return $builder->get();
    }

    /**
     * Finds a job based by id
     *
     * @param $jobId
     * @return \Illuminate\Database\Eloquent\Collection|Model|CronJob|CronJob[]|null
     */
    public static function findById($jobId)
    {
        return self::find($jobId);
    }
}
